# New Section

In [1]:
# Import required packages
import pandas as pd
import numpy as np

In [2]:
# Read the data
data = pd.read_excel('/Users/saikirananugam/Desktop/meg_fello/dataset72ann.xlsx')
data.head()

caste   rank gender branch
0      0  15733      m    cse
1      0  13808      f    cse
2      1  36314      m    cse
3      1  42674      f    cse
4      2  23781      m    cse

In [3]:
data.describe()

caste          rank
count  71.000000     71.000000
mean    3.535211  57221.816901
std     2.413243  21713.438531
min     0.000000  13808.000000
25%     1.000000  35580.000000
50%     4.000000  64780.000000
75%     6.000000  74757.500000
max     7.000000  94518.000000

In [4]:
# Convert gender into numeric data
gender = data.gender.unique()
data['gender'].replace(gender, range(len(gender)), inplace=True)
print(gender)
data.head()
# m = 0
# f = 1

['m' 'f']


caste   rank  gender branch
0      0  15733       0    cse
1      0  13808       1    cse
2      1  36314       0    cse
3      1  42674       1    cse
4      2  23781       0    cse

In [5]:
# Proceed for training ANN


# Apply dummy coding on label (branch)
dummies = pd.get_dummies(data.branch)
data = pd.concat([data, dummies], axis = 1)
data.drop(['branch'], axis = 1, inplace = True)

data.head()

caste   rank  gender  ce  cse  ece  eee  me
0      0  15733       0   0    1    0    0   0
1      0  13808       1   0    1    0    0   0
2      1  36314       0   0    1    0    0   0
3      1  42674       1   0    1    0    0   0
4      2  23781       0   0    1    0    0   0

In [6]:
# Split features and label
x = data.drop(['ce', 'cse', 'ece', 'eee', 'me'], axis=1)
y = data[['ce', 'cse', 'ece', 'eee', 'me']].to_numpy()

In [7]:
x

caste   rank  gender
0       0  15733       0
1       0  13808       1
2       1  36314       0
3       1  42674       1
4       2  23781       0
..    ...    ...     ...
66      5  56372       0
67      6  86143       0
68      6  94518       1
69      7  82697       0
70      7  70741       1

[71 rows x 3 columns]

In [8]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
x=ms.fit_transform(x)
print(x)

[[0.         0.02385082 0.        ]
 [0.         0.         1.        ]
 [0.14285714 0.2788502  0.        ]
 [0.14285714 0.35765085 1.        ]
 [0.28571429 0.12356585 0.        ]
 [0.28571429 0.16551852 1.        ]
 [0.42857143 0.61298476 0.        ]
 [0.42857143 0.16546896 1.        ]
 [0.57142857 0.11742039 0.        ]
 [0.57142857 0.11294759 1.        ]
 [0.71428571 0.22116219 0.        ]
 [0.71428571 0.27229587 1.        ]
 [0.85714286 0.33206542 0.        ]
 [0.85714286 0.48884897 1.        ]
 [1.         0.24497584 0.        ]
 [1.         0.37752447 1.        ]
 [0.         0.10019824 0.        ]
 [0.         0.12543675 1.        ]
 [0.14285714 0.67196134 0.        ]
 [0.14285714 0.46456449 1.        ]
 [0.28571429 0.30546401 0.        ]
 [0.28571429 0.26721596 1.        ]
 [0.57142857 0.25689506 0.        ]
 [0.57142857 0.26499814 1.        ]
 [0.71428571 0.66249535 0.        ]
 [0.71428571 0.50579854 1.        ]
 [0.85714286 0.74899021 0.        ]
 [0.85714286 0.82779086 1.  

In [9]:
# Split data for training and testing
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=101)


In [10]:
ytrain

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1,

In [11]:
from keras.models import Sequential
from keras.layers import Dense

# Initialization of ANN model
model=Sequential()
model.add(Dense(30,activation='tanh', input_shape=(3,)))
model.add(Dense(30,activation='tanh'))
model.add(Dense(5,activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                120       
                                                                 
 dense_1 (Dense)             (None, 30)                930       
                                                                 
 dense_2 (Dense)             (None, 5)                 155       
                                                                 
Total params: 1,205
Trainable params: 1,205
Non-trainable params: 0
_________________________________________________________________


2022-04-30 22:14:20.390514: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [12]:
# Training the model
history = model.fit(xtrain, ytrain, batch_size=1, epochs=1000, verbose=1)

Epoch 1/1000
56/56 [==============================] - 0s 978us/step - loss: 1.6373 - accuracy: 0.2857
Epoch 2/1000
56/56 [==============================] - 0s 999us/step - loss: 1.5582 - accuracy: 0.2857
Epoch 3/1000
56/56 [==============================] - 0s 793us/step - loss: 1.5261 - accuracy: 0.2857
Epoch 4/1000
56/56 [==============================] - 0s 839us/step - loss: 1.4978 - accuracy: 0.3393
Epoch 5/1000
56/56 [==============================] - 0s 820us/step - loss: 1.4631 - accuracy: 0.4107
Epoch 6/1000
56/56 [==============================] - 0s 841us/step - loss: 1.4317 - accuracy: 0.4464
Epoch 7/1000
56/56 [==============================] - 0s 761us/step - loss: 1.4019 - accuracy: 0.3929
Epoch 8/1000
56/56 [==============================] - 0s 836us/step - loss: 1.3793 - accuracy: 0.3929
Epoch 9/1000
56/56 [==============================] - 0s 869us/step - loss: 1.3493 - accuracy: 0.3929
Epoch 10/1000
56/56 [==============================] - 0s 783us/step - loss: 1.321

In [13]:
history.history['accuracy']

[0.2857142984867096,
 0.2857142984867096,
 0.2857142984867096,
 0.3392857015132904,
 0.4107142984867096,
 0.4464285671710968,
 0.3928571343421936,
 0.3928571343421936,
 0.3928571343421936,
 0.3928571343421936,
 0.3928571343421936,
 0.3928571343421936,
 0.3928571343421936,
 0.4285714328289032,
 0.4107142984867096,
 0.4464285671710968,
 0.3928571343421936,
 0.4285714328289032,
 0.4285714328289032,
 0.4107142984867096,
 0.4464285671710968,
 0.3928571343421936,
 0.5,
 0.4821428656578064,
 0.4642857015132904,
 0.3928571343421936,
 0.4642857015132904,
 0.4642857015132904,
 0.4642857015132904,
 0.5,
 0.4285714328289032,
 0.4642857015132904,
 0.5,
 0.4285714328289032,
 0.4821428656578064,
 0.4285714328289032,
 0.4285714328289032,
 0.4642857015132904,
 0.5,
 0.4642857015132904,
 0.4642857015132904,
 0.4642857015132904,
 0.5,
 0.5357142686843872,
 0.5,
 0.4642857015132904,
 0.4821428656578064,
 0.4821428656578064,
 0.4285714328289032,
 0.5178571343421936,
 0.5,
 0.5,
 0.4821428656578064,
 0.5178

In [14]:
model.predict(xtrain[:5])

array([[3.87785234e-03, 1.26454047e-08, 9.16186273e-01, 2.85876039e-02,
        5.13482206e-02],
       [1.34226859e-01, 1.60951027e-12, 3.14316243e-01, 5.53249307e-02,
        4.96131957e-01],
       [4.08074747e-08, 9.99994159e-01, 5.83111978e-06, 1.75120107e-09,
        5.73489656e-09],
       [5.76676965e-01, 2.07069435e-14, 1.07475124e-01, 1.39559001e-01,
        1.76289037e-01],
       [1.93010449e-01, 1.38603213e-13, 1.92917123e-01, 2.22874627e-01,
        3.91197801e-01]], dtype=float32)

In [ ]:
xtrain[:5]

array([[0.28571429, 0.26721596, 1.        ],
       [0.71428571, 0.52736959, 0.        ],
       [0.        , 0.        , 1.        ],
       [0.85714286, 0.74899021, 0.        ],
       [1.        , 0.70540206, 1.        ]])

In [21]:
import pickle
# Save the model
filename = 'model.pkl'
pickle.dump(model, open(filename, 'wb'))

INFO:tensorflow:Assets written to: ram://e2754867-927e-4924-8e41-16b3eaad2238/assets


In [16]:
model.save("branchpred.h5")

In [20]:
caste = ['oc', 'bc-a', 'bc-b', 'bc-c', 'bc-d', 'bc-e', 'sc', 'st']
gender = ['m', 'f']
branch = ['cse', 'ece', 'eee', 'ce', 'me']
inputData = pd.DataFrame(columns=['caste', 'rank', 'gender'])
casteInput = input('Enter the caste :')
rankInput = int(input('Enter the rank :'))
rankInputs=(rankInput-13808)/(94518-13808)
genderInput = input('Enter the gender :')
casteInput = caste.index(casteInput)
casteInputs=(casteInput-0)/7;
genderInput = gender.index(genderInput)

from keras.models import load_model
model = load_model('/Users/saikirananugam/Desktop/meg_fello/model.pkl')

modelInput = [casteInputs,rankInputs, genderInput]
h=model.predict([modelInput])
labels = ['ce', 'cse', 'ece', 'eee', 'me']
print('branch :',labels[model.predict([modelInput]).argmax(axis=1)[0]])



OSError: SavedModel file does not exist at: /Users/saikirananugam/Desktop/meg_fello/model.pkl/{saved_model.pbtxt|saved_model.pb}

In [ ]:
casteInput

0